### ISSUE TITLE
check-docs type-checks doc examples instead of compiling them: 14 of 187 "must compile" blocks do not build

### ISSUE THREAD

**Issue by nicolas-maman** [nicolasmd87/aether#1878]
`tests/scripts/check_doc_blocks.py` says a bare ```` ```aether ```` block is *"a complete program. Must compile. CHECKED HERE."* It does not compile it. `compiles()` runs `ae check`, which is the front end only:

```python
r = subprocess.run([ae, "check", path], capture_output=True, timeout=120)
```

So any documented example that type-checks but cannot be code-generated passes the gate. `run` blocks are fine, `runs()` calls `ae run`, which does build.

## The example that exposed it

`docs/hide-and-seal.md:85`, discussed in #1851:

```
$ ae check block.ae   ->  OK: no errors        (exit 0)
$ ae build block.ae   ->  error: use of undeclared identifier 'secret_token'   (exit 1)
```

Worth recording, because #1851 spent time on this as a suspected regression from the #1855 scope fix: **it is not a regression.** The same block fails to build at `100b540b` (the `v0.621.0` merge, immediately before #1851 landed). Codex's scope isolation did not break it, it moved the failure from codegen up into the typechecker, which is the one layer this gate can see. The narrow fix in `40fb1505` moved it back down, where the gate is blind again.

`hide` and `seal except` themselves are fine and need no rethink. On `114b6d44`:

| program | result |
| --- | --- |
| `hide token`, name unused in the block | builds, runs |
| `hide token`, then read `token` | `error[E0304]: 'token' is hidden in this scope` |
| `seal except keep, println`, read `keep` | builds, runs |
| `seal except keep, println`, read `drop` | `error[E0304]: 'drop' is hidden in this scope` |

Only the "does NOT reach through call boundaries" paragraph is wrong, and it describes something codegen has never implemented.

## The full sweep

Every non-`fragment`, non-`fails` block through `ae check` and then `ae build`, on `114b6d44`, macOS 15 / arm64, clang from CommandLineTools:

```
blocks passing `ae check`: 241   (187 bare + 54 run)
of those, failing `ae build`:  14
```

**Eight fail only at link**, because they `extern` C the block does not supply (`_my_add`, `_my_greet`, `_my_power`, `_ws_generate_accept_key`, `_ws_unmask`). Those are not compiler bugs, but they are also not "complete programs", so they need a label or a companion object:

`docs/c-interop.md` lines 82, 124, 192, 451, 520, 599, 1062, and `docs/liveview-lite-roadmap.md:499`.

**Six fail in the C compiler.** Each reduced to a minimal repro that reproduces the failure on its own:

| block | `ae build` error | reduced cause |
| --- | --- | --- |
| `docs/hide-and-seal.md:85` | `use of undeclared identifier 'secret_token'` | a function reading a caller's local via the lexical chain is documented but not implemented |
| `docs/isolated.md:16` | `unknown type name 'Payload'` | `ae check` accepts an **undefined type in a signature** |
| `docs/language-reference.md:125` | `conflicting types for 'strtold'` | the `extern` emits `long double strtold(const char*, void*)`; the SDK declares `char **__restrict` as the second parameter |
| `docs/tutorials/02-functions-and-control-flow.md:455` | `conflicting types for 'abs'` | empty body infers `void`, so `void abs(int)` collides with libc's `int abs(int)` |
| `docs/tutorials/02-functions-and-control-flow.md:485` | `argument type 'void' is incomplete` | same root: a void-returning function used as a value |
| `std/tcp/README.md:13` | `invalid operands ('_tuple_int_string' and 'char[1]')` | `werr = tcp.write(...)` binds a **2-value return to one name** |

Note on `abs`: it is **not** a reserved-name/mangling problem. `abs(n: int) -> int { ... }` with a real body builds fine. Renaming the empty-bodied one to `zzz` gives `argument type 'void' is incomplete`, the same error as 485. The `abs` wording is just clang comparing against libc's declaration.

## Front-end holes underneath

Four of the six are one shape: `ae check` accepts a program the code generator cannot express. Each verified standalone (`check=OK`, `build=FAIL`):

```aether
// 1. undefined type name in a signature
f(p: Nonexistent) -> int { return 1 }
main() { println("hi") }
```

```aether
// 2. two-value return bound to one name
two() -> { return 1, "" }
main() {
    x = two()
    if x != "" { println("no") }
}
```

```aether
// 3. empty body infers void, then used as a value
power(x, n) {
}
main() { print(power(2, 3)) }
```

The third is the shape the tutorial's own exercise stubs take, so it is worth deciding whether an unfinished body is an error or an inferred `void`.

Case 2 is the one I would prioritise. It is the same family as #1855: the front end waves through something whose only symptom is `invalid operands to binary expression` deep in generated C, which is exactly how #1855 presented and how long it took to find. #1855 itself is genuinely fixed (`tests/regression/test_if_else_branch_scope.ae` passes 4/4 here, `make test` 409/409, `check-docs` exit 0), but the shape that produced it is still reachable from a two-line program.

## Suggested order

1. Make the gate build. Expect it to go red on 14 blocks, so land it with the labels/fixes below in the same change.
2. Label or supply C for the eight link-only blocks.
3. Fix `std/tcp/README.md:13` to `n, werr = tcp.write(...)`, and correct the `hide-and-seal.md` paragraph to describe what actually happens.
4. Reject cases 1 to 3 in the front end, so they stop being discoverable only as clang errors.

## Environment

`114b6d44` (v0.627.0), macOS 15.6 arm64, Apple clang. `make -j8 all` clean, `make test` 409/409, `make check-docs` exit 0 — which is the point: the gate is green while 14 of its 187 "must compile" blocks do not compile.
